# Generated by Django 5.2.4 on 2025-07-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactMessage",
            new_name="Contact",
        ),
    ]
