# Generated by Django 5.2.4 on 2025-07-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_remove_service_slug_service_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(default=1, upload_to="services/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
